### ISSUE TITLE
Python version confusion?

### ISSUE THREAD

**Issue by scuerda** [CityOfBoston/CityScoreToolkit#1]
The `Dockerfile` indicates python:3 as the version to pull but the "build from source" instructions reference 2.7. Should clarify which is the preferred version (3?)

**Comment by therriault** [comment]
cc: @alchenist 

This was a recent change, I believe the final version is built out on 2.7 but will check.

**Comment by alchenist** [comment]
The code was intended for 2.7, but I've been running it in Python 3 with no ill effects (thanks, Django). Nevertheless, I'll change the Dockerfile to rely on the python:2 base image for consistency.
